name: Deployment Job
on: 
    workflow_call:
        inputs:
            WEB_URL: 
                required: true
                type: string
            S3_URL:
                required: true
                type: string
        secrets:
            AWS_ACCESS_KEY_ID:
                required: true
            AWS_SECRET_ACCESS_KEY:
                required: true    

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps: 
          - uses: actions/checkout@v4
          - uses: actions/download-artifact@v4
          - uses: actions/setup-python@v2
            with:
                python-version: '3.10'
          - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                pip install awscli
          - name: Run AWS CLI Commands
            run: |
                echo "You're in AWS Cli mode"
                aws --version
                ls -l
                aws s3 sync build ${{ inputs.S3_URL }} --delete
            env: 
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          - name: Test for working website
            run: |
                echo ${{github.run_id}}
                echo ${{ inputs.WEB_URL }}/version.html
                curl ${{ inputs.WEB_URL }}/version.html | grep "${{github.run_id}}"      
